name: CI

on: [push]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Prepare
      run: |
        curl -vLo http://www.adammil.net/files/133/bbros.zip
        Expand-Archive bbros.zip
        cp bbros/bin/* . && rm -Rf bbros/ bbros.zip
    - name: Compile
      working-directory: build
      run: masscompile.bat
